services:
  NoPersaPostgresDb:
    image: postgres:latest
    container_name: PostgresDb
    ports:
        - "5432:5432"
    restart: always
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
        - NoPersaPostgresDb-data:/var/lib/postgresql/data

  nopersaservice:
    image: ${DOCKER_REGISTRY-}nopersaservice
    container_name: NoPersaService
    build:
      context: .
      dockerfile: NoPersaService/Dockerfile
    ports:
      - "8081:8081"
    pull_policy: always
    restart: always
    depends_on:
      - NoPersaPostgresDb
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - HOLIDAY_API=${HOLIDAY_API}
      - ROUTING_API=${ROUTING_API}

  website.server:
    image: ${DOCKER_REGISTRY-}websiteserver
    container_name: Website
    build:
      context: .
      dockerfile: Website/Server/Dockerfile
    ports:
      - "7039:7039"
    restart: always

volumes:
  NoPersaPostgresDb-data:

